# Generated by Django 5.1.4 on 2024-12-29 06:26

import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100)),
                ('service_description', tinymce.models.HTMLField()),
                ('service_image', versatileimagefield.fields.VersatileImageField(upload_to='service')),
            ],
        ),
    ]
