# Generated by Django 5.1.4 on 2024-12-29 07:46

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_image',
            new_name='service_gif_image',
        ),
        migrations.AddField(
            model_name='service',
            name='service_main_image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='service'),
            preserve_default=False,
        ),
    ]
