# Generated by Django 5.1.4 on 2024-12-29 08:08

import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_service_image_service_service_gif_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=100)),
                ('gallery_date', models.DateTimeField()),
                ('gallery_description', tinymce.models.HTMLField()),
                ('gallery_image', versatileimagefield.fields.VersatileImageField(upload_to='gallery')),
            ],
        ),
    ]
