# Generated by Django 5.1.4 on 2024-12-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
