# Generated by Django 5.1.4 on 2024-12-30 10:55

import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_gallery_gallery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film_Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=100)),
                ('film_image', versatileimagefield.fields.VersatileImageField(upload_to='gallery')),
                ('who_we_are', tinymce.models.HTMLField()),
                ('where_we_are', tinymce.models.HTMLField()),
                ('what_you_get', tinymce.models.HTMLField()),
                ('choose_your_competition', tinymce.models.HTMLField()),
                ('who_we_want', tinymce.models.HTMLField()),
                ('what_we_accept', tinymce.models.HTMLField()),
                ('terms_and_regulations', tinymce.models.HTMLField()),
            ],
        ),
    ]
