# Generated by Django 5.1.4 on 2025-01-02 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='csr_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CSRAddOnContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=200)),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='csr_addon_images/')),
                ('csr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_on_contents', to='web.csr')),
            ],
        ),
    ]
