# Generated by Django 5.1.4 on 2025-01-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Media_Image',
        ),
    ]
