# Generated by Django 5.1.4 on 2025-01-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_media_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='url',
            field=models.URLField(),
        ),
    ]
